config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/tags' => 'pages#tags', as: 'tags'
  get '/tag_search' => 'pages#tags_search', as: 'tags_search'
  post '/notes/new' => 'contacts#create_note', as: 'notes'
  delete '/notes/:slug/delete' => 'contacts#delete_note', as: 'delete_note'
  resources :contacts, param: :slug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :tags, dependent: :destroy
  has_many :notes, dependent: :destroy
  before_create :generate_slug
  has_one_attached :avatar

  def generate_slug
    self.slug = SecureRandom.urlsafe_base64(6)
  end


  COUNTRIES_LIST = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo (the Democratic Republic of the)",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands [Malvinas]",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States Minor Outlying Islands",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands"
  ]
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :contact
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :contact
  before_create :generate_slug

  def generate_slug
    self.slug = SecureRandom.urlsafe_base64(6)
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include BirthdaysHelper
end

app/controllers/contacts_controller.rb
require 'json'
class ContactsController < ApplicationController
  before_action :set_contact, only: [:edit, :update, :show, :destroy]
  before_action :set_tags, only: [:create, :update]
  def new
    @contact = Contact.new
    @tags = Tag.all.map{|x| x.name}.uniq
  end

  def create
    @contact = Contact.new(contacts_params.except(:tags))
    if @contact.save
      redirect_to root_path
      @tags.each do |tag|
        Tag.find_or_create_by(contact_id: @contact.id, name: tag)
      end
    end
  end

  def edit
    @contact = Contact.find_by(slug: params[:slug])
  end

  def show
    @note = Note.new
    @notes = Note.find_by(slug: params[:slug])
  end

  def update
    if @contact.update(contacts_params.except(:tags))
      old_tags = @contact.tags
      old_tags.each do |tag|
        next if @tags.include?(tag.name)
        tag.destroy
      end
      @tags.each do |tag|
        Tag.find_or_create_by(contact_id: @contact.id, name: tag)
      end
      redirect_to "/contacts/#{@contact.slug}"
    end

  end

  def destroy
    if @contact.destroy
      @contact.avatar.purge
      redirect_to root_path
    end
  end

  def create_note
    @note = Note.create(notes_params)
    respond_to do |format|
      format.js
      format.html do
        redirect_to request.referrer
      end
    end
  end

  def delete_note
    @note = Note.find_by(slug: params[:slug])
    @note.destroy
    respond_to do |format|
      format.js
      format.html do
        redirect_to request.referrer
      end
    end
  end

  private

  def set_tags
    @tags = JSON.parse(contacts_params[:tags]).map{|x| x["value"]}
  end

  def set_contact
    @contact = Contact.find_by(slug: params[:slug]) || Contact.find_by_id!(params[:slug])
  end

  def contacts_params
    params.require(:contact).permit(:slug, :avatar, :first_name, :last_name, :email, :phone_number, :city, :country, :address_1, :address_2, :relationship, :birthday, :personal_website, :occupation, :company_website, :tags, :industry, :state)
  end

  def notes_params
    params.require(:note).permit(:contact_id, :description, :slug)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @pagy, @contacts = pagy(Contact.all)
  end

  def tags
    @tags = Tag.all.map{|x| x.name}.uniq
  end

  def tags_search
    @tag = Tag.find_by(name: params[:tag])
    @contacts = Tag.where(name: @tag.name).map{|x| x.contact}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/birthdays_helper.rb
module BirthdaysHelper
  def contacts_birthdays
    @current_year = Date.today.year
    @current_month = Date.today.month
    Contact.all.select{|c| c.birthday.strftime('%m').to_i == @current_month}.sort_by(&:birthday)
  end
end

app/views/contacts/_contact_form.html.erb
<%= form_with model: @contact do |f| %>

  <div class="mb-16">
    <div class="w-full border-b relative">
      <div class="rounded-full bg-gray-400 h-24 w-24 flex justify-center items-center absolute" style="top: -3em; left: 43.5%;">
        <div class="relative">
          <div id="avatar">
            <% if @contact.avatar.present? %>
              <%= image_tag(@contact.avatar, class: "rounded-full w-24 h-24") %>
            <% else %>
              <svg id="avatar-placeholder" fill="none" viewBox="0 0 24 24" stroke="#fafafa" class="user w-12 h-12"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
            <% end %>
          </div>

        </div>
        <div class="absolute" style="right: 10%; bottom: -2px;">
            <%= f.label :avatar, '', class: 'h-5 w-5 bg-white rounded-full shadow flex justify-center items-center focus:outline-none hover:bg-green-100 cursor-pointer' do %>
              <%= f.file_field :avatar, accept: 'image/jpeg', onchange: 'previewImage(this);' %>
              <svg viewBox="0 0 20 20" fill="currentColor" class="pencil w-3 h-3"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path></svg>
            <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="flex">
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 mr-2">
      <%= f.text_field :first_name, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :first_name, 'First Name', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 ml-2">
      <%= f.text_field :last_name, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :last_name, 'Last Name', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>
  </div>
  <div class="flex">
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 mr-2">
      <%= f.text_field :email, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :email, 'Email Address', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 ml-2">
      <%= f.text_field :phone_number, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :phone_number, 'Phone Number', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>
  </div>
  <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2">
    <%= f.text_field :personal_website, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
    <%= f.label :personal_website, 'Personal Website', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
  </div>

    <span class="pb-6 relative">
      <label class="absolute bg-white p-1 duration-300 origin-0 text-sm" style="bottom: -1em; left:0.8em; z-index: 9999">
        Tags
      </label>
    </span>
    <input name='contact[tags]' class='tagify-custom text-lg' placeholder='write some tags' value='<%= @contact.tags.map(&:name).join(", ") %>'></input>

  <hr>
  <br>
  <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2">
    <%= f.date_field :birthday, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
    <%= f.label :birthday, 'Birthday', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
  </div>

  <hr>
  <br>

  <div class="flex">
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 mr-2">
      <%= f.text_field :city, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :city, 'City', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 ml-2">
      <%= f.text_field :state, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :state, 'State/Province', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>

  </div>
  <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 p-4" style="width: 68%">
    <%= f.select :country, Contact::COUNTRIES_LIST,  class: "block p-4 text-lg appearance-none outline-none", placeholder: "" %>
    <%= f.label :country, 'Country', class: "absolute top-0 bg-white p-1 z-1 duration-300 origin-0 text-sm", style: "top: -16px; left: 2%" %>
  </div>

  <div class="flex">
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 mr-2">
      <%= f.text_field :address_1, class: "block p-4 w-full text-lg appearance-none hover:outline-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :address_1, 'Address 1', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 ml-2">
      <%= f.text_field :address_2, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :address_2, 'Address 2', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>
  </div>

  <hr>
  <br>


  <div class="flex">
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 mr-2">
      <%= f.text_field :occupation, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :occupation, 'Occupation', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>
    <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 ml-2">
      <%= f.text_field :industry, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
      <%= f.label :industry, 'Industry', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
    </div>
  </div>
  <div class="outline relative border-2 focus-within:border-blue-400 mt-2 mb-6 w-1/2 mr-2">
    <%= f.text_field :company_website, class: "block p-4 w-full text-lg appearance-none focus:outline-none bg-transparent", placeholder: "" %>
    <%= f.label :company_website, 'Company Website', class: "absolute top-0 text-lg bg-white p-4 -z-1 duration-300 origin-0" %>
  </div>

  <br>

  <div class="flex justify-between items-center">
    <%= f.submit 'save_contact', class: ' bg-blue-500 hover:bg-blue-400 text-white py-4 px-10 rounded hover:shadow-sm', data: { disable_with: "saving..." } %>
    <% if @contact.slug.present? %>
      <%= link_to 'delete_contact', contact_path(slug: @contact.slug), method: :delete, data: { confirm: "Are you sure you want to delete #{@contact.first_name}?", disable_with: 'deleting...', slug: @contact.slug }, class: "delete-note bg-red-500 hover:bg-red-400 text-white p-2 rounded hover:shadow-sm text-xs" %>
    <% end %>
  </div>
<% end %>


<script>
  function previewImage(e) {
    var fileList = e.files
    var last_image = fileList[fileList.length - 1]
    var file = URL.createObjectURL(last_image);
    var placeholder = document.querySelector('#avatar-placeholder');
    var avatar = document.querySelector('#avatar');
    if (file) {
      if (placeholder) {
        placeholder.style.display = 'none';
      }
      avatar.innerHTML = '<img src="' + file + '" class="rounded-full object-cover h-24 w-24" />';
    }
  }

  var tags = <%= raw @tags.to_json %>;
  var input = document.querySelector('input[name="contact[tags]"]'),
    tagify = new Tagify(input, {
      whitelist: tags,
      dropdown : {
        position: 'text',
        enabled: 1
      },
  })
</script>

app/views/contacts/_note.html.erb
<article id="note-<%= n.slug %>">
  <div class="my-4">
    <div class="flex justify-between items-center">
      <%= n.created_at.strftime("%m""/""%d""/""%Y") %>
      <%= button_to 'delete_note', delete_note_path(slug: n.slug), method: :delete, data: { confirm: 'Are you sure?', disable_with: 'deleting...', slug: n.slug }, remote: true, class: "delete-note bg-red-500 hover:bg-red-400 text-white p-2 rounded hover:shadow-sm text-xs" %>
    </div>
    <br>
    <%= n.description %>
  </div>
  <hr>
</article>

app/views/contacts/show.html.erb
<div class="clearfix">
  <%= render 'shared/sidebar' %>
  <main class="float-right w-5/6 ">
    <p class="font-semibold mb-6">Contact Information</p>
    <div class="mb-16">
      <div class="w-full border-b relative">
        <div class="rounded-full bg-gray-400 h-24 w-24 flex justify-center items-center absolute" style="top: -3em; left: 43.5%;">
          <% if @contact.avatar.present? %>
            <%= image_tag(@contact.avatar, class: "rounded-full w-24 h-24") %>
          <% else %>
            <svg id="avatar-placeholder" fill="none" viewBox="0 0 24 24" stroke="#fafafa" class="user w-12 h-12"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
          <% end %>
        </div>
      </div>
    </div>
    <section>
      <div class="flex w-full justify-end">
        <%= link_to "edit_contact_info", edit_contact_path(slug: @contact.slug), class: "bg-blue-500 hover:bg-blue-400 text-white p-2 rounded hover:shadow-sm"%>
      </div>
      <small>Name</small>
      <p class="text-lg"><%= @contact.first_name %> <%= @contact.last_name %></p>
      <small>Email</small>
      <p class="text-lg"><%= @contact.email %></p>
      <small>Phone Number</small>
      <p class="text-lg"><%= @contact.phone_number %></p>
      <small>Personal Website</small>
      <p class="text-lg"><%= @contact.personal_website %></p>
      <small>Address 1</small>
      <p class="text-lg"><%= @contact.address_1 %></p>
      <small>Address 2</small>
      <p class="text-lg"><%= @contact.address_2 %></p>
      <small>City, State/Province, Country</small>
      <p class="text-lg"><%= @contact.city %>, <%= @contact.state %>, <%= @contact.country %></p>
      <small>Occupation</small>
      <p class="text-lg"><%= @contact.occupation %></p>
      <small>Industry</small>
      <p class="text-lg"><%= @contact.industry %></p>
      <small>Company Website</small>
      <p class="text-lg"><%= @contact.company_website %></p>
      <small>Tags</small>
      <p>
      <% @contact.tags.each do |t|  %>
        <%= link_to tags_search_path(tag: t.name) do %>
          <div class="tag-button rounded duration-300 inline-block"><%= t.name %></div>
        <% end %>
      <% end %>
      </p>
    </section>
    <hr class="my-4">
    <section>
      <p class="font-semibold mb-6">Notes</p>
      <%= render 'note_form' %>
      <div id="contactnote">
        <% @contact.notes.order(created_at: 'desc').each do |n| %>
          <div><%= render "note", n: n %></div>
        <% end %>
      </div>
    </section>
  </main>
</div>

app/views/layouts/_navbar.html.erb
<nav class="w-full bg-white border-b-2 py-4 px-2 md-px-0">
  <div class="max-w-4xl mx-auto">
    <div class="flex items-center justify-between">
      <div>people.db</div>
      <div>
        <%= link_to 'new_contact', new_contact_path, class: 'inline-block mr-4 rounded-md border p-2 bg-blue-500 hover:bg-blue-400 text-white outline-none' %>
        <div class="inline-block">sign_out</div>
      </div>
    </div>
  </div>
</nav>

app/views/pages/home.html.erb
<div class="clearfix">
  <%= render 'shared/sidebar' %>
  <main class="float-right w-5/6 ">
    <p class="font-semibold mb-6">Your Contacts</p>
    <table class="table-fixed w-full">
      <thead>
        <tr>
          <th class="w-1/3 pb-2 text-left text-xs">Name</th>
          <th class="w-1/3 pb-2 text-left text-xs">Last contacted</th>
          <th class="w-1/3 pb-2 text-left text-xs">Location</th>
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |c| %>
          <tr class="border-t-2 border-b-2">
            <td class=" px-4 py-2">
              <%= link_to contact_path(slug: c.slug), class: 'hover:text-blue-500' do %>
                <% if c.avatar.present? %>
                  <%= image_tag(c.avatar, class: "rounded-full w-6 h-6 inline-block align-middle") %>  <span class="inline-block align-middle"><%= c.first_name %> <%= c.last_name %></span>
                <% else %>
                  <svg id="avatar-placeholder" fill="none" viewBox="0 0 24 24" stroke="#fafafa" class="p-1 rounded-full inline-block align-middle user w-6 h-6 bg-gray-400"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg> <span class="inline-block align-middle"><%= c.first_name %> <%= c.last_name %></span>
                <% end %>
              <% end %>
              </td>
            <td class=" px-4 py-2">-</td>
            <td class="text-sm px-4 py-2"><%= c.city %>, <%= c.country %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="my-4 text-center">
      <%== pagy_nav(@pagy) %>
    </div>
  </main>
</div>

app/views/pages/tags.html.erb
<div class="clearfix">
  <%= render 'shared/sidebar' %>
  <main class="float-right w-5/6 ">
    <p class="font-semibold mb-6">Tags</p>
    <section>
      <% @tags.each do |t| %>
        <%= link_to tags_search_path(tag: t) do %>
          <div class="tag-button rounded duration-300 inline-block"><%= t %></div>
        <% end %>
      <% end %>

    </section>
  </main>
</div>

<style>

</style>

app/views/pages/tags_search.html.erb
<div class="clearfix">
  <%= render 'shared/sidebar' %>
  <main class="float-right w-5/6 ">
    <p class="font-semibold mb-6">Contacts found with <span class="tag-button rounded duration-300 font-normal"><%= @tag.name %></span></p>
    <section>
      <% @contacts.each do |c| %>
        <%= link_to contact_path(slug: c.slug) do %>
          <div class="flex items-center hover:bg-blue-100 p-2 rounded duration-300">
            <% if c.avatar.present? %>
              <%= image_tag(c.avatar, class: "rounded-full w-24 h-24") %>
            <% else %>
              <svg id="avatar-placeholder" fill="none" viewBox="0 0 24 24" stroke="#fafafa" class="p-4 rounded-full inline-block align-middle user w-24 h-24 bg-gray-400"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
            <% end %>
            <div class="flex-1 pl-4">
              <div><%= c.first_name %> <%= c.last_name %></div>
              <div><%= c.city %>, <%= c.state %>, <%= c.country %></div>
            </div>
          </div>
        <% end %>
        <hr class="my-4">
      <% end %>
    </section>
  </main>
</div>

app/views/shared/_sidebar.html.erb
<aside class="float-left mt-8 w-1/6 pr-8 sticky top-0">
  <ul>
    <%= link_to root_path do %>
      <li class="mb-2 hover:text-blue-500">your_contacts</li>
    <% end %>
    <%= link_to tags_path do %>
    <li class="mb-2 hover:text-blue-500">contact_tags</li>
    <% end %>
    <li class="mb-2 text-green-600"><%= Time.now.strftime("%b").downcase %>_birthdays</li>
    <ul>
    <% contacts_birthdays.each do |x| %>
      <%= link_to contact_path(slug: x.slug) do %>
      <li class="text-xs mb-2 p-1 hover:bg-blue-100">
        <div><%= x.first_name.capitalize%> <%= x.last_name.capitalize%></div>
        <%= x.birthday.strftime("%b %d, %Y") %><br><%= @current_year - x.birthday.strftime('%Y').to_i + 1 %> years old
      </li>
      <% end %>
      <hr class="my-2">
    <% end %>
    </ul>
  </ul>
</aside>